<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- Aspire packages -->
    <PackageVersion Include="Aspire.StackExchange.Redis.DistributedCaching" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.Azure.AppContainers" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.Azure.Redis" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.Docker" Version="13.0.0-preview.1.25560.3" />
    <PackageVersion Include="Aspire.Hosting.Redis" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.SqlServer" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.JavaScript" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.Yarp" Version="13.0.0" />
    <PackageVersion Include="Aspire.Hosting.Maui" Version="13.0.0-preview.1.25560.3" />
    <PackageVersion Include="Aspire.Hosting.DevTunnels" Version="13.0.0-preview.1.25560.3" />
    <!-- Microsoft packages -->
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.0.0" />
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.10" />
    <!-- OpenTelemetry packages -->
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.14.0" />
    <!-- Miscellaneous packages -->
    <PackageVersion Include="Scalar.AspNetCore" Version="2.10.3" />
  </ItemGroup>
</Project>